import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import navbar2 from './_components/navbar2';
import Header from "./_components/navbar2";
import Footer from "./_components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Header/>
        </div>
        {children}
        <div className="flex justify-center">
          <Footer/>
        </div>
      </body>
    </html>
  );
}
